/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#37485b",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d2e4fb",
        "on-secondary-container": "#536478",
        "on-primary-fixed": "#1b1b1c",
        "tertiary": "#000000",
        "on-primary-container": "#858384",
        "outline": "#76777b",
        "on-tertiary-fixed": "#1c1b19",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#484644",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474647",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f4f0ef",
        "inverse-primary": "#c8c6c7",
        "primary-fixed-dim": "#c8c6c7",
        "on-surface-variant": "#46474a",
        "surface-container-low": "#f7f3f2",
        "surface-tint": "#5f5e5f",
        "tertiary-fixed-dim": "#cac6c2",
        "surface": "#fdf8f8",
        "surface-variant": "#e5e2e1",
        "on-error-container": "#93000a",
        "secondary-container": "#cfe1f8",
        "surface-container": "#f1edec",
        "secondary-fixed-dim": "#b6c8df",
        "on-primary": "#ffffff",
        "on-surface": "#1c1b1b",
        "primary-container": "#1b1b1c",
        "tertiary-fixed": "#e6e2de",
        "surface-bright": "#fdf8f8",
        "surface-dim": "#ddd9d9",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#0a1d2d",
        "surface-container-highest": "#e5e2e1",
        "error": "#ba1a1a",
        "background": "#fdf8f8",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4f6073",
        "outline-variant": "#c7c6ca",
        "on-tertiary-container": "#868380",
        "primary-fixed": "#e5e2e3",
        "inverse-surface": "#313030",
        "tertiary-container": "#1c1b19",
        "surface-container-high": "#ebe7e7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "unit": "8px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
